Added support an intra-cell-newlines; fix #3
csholmq/vscode-excel-to-markdown-table pull request #15
Opened 2020-01-08 03:47 UTC by usagi

2020-01-18 01:57 UTC, usagi commented
@csholmq ping

2020-01-18 22:55 UTC, csholmq requested changes
Looking very nice!

Which platforms have you tested this on?

2020-01-18 22:55 UTC, csholmq commented on src/excel-markdown-helpers.ts
> +const UNESCAPED_DOUBLE_QUTE = '"';
QUOTE*

2020-01-18 22:55 UTC, csholmq commented on src/excel-markdown-helpers.ts
> +const MARKDOWN_INTRA_CELL_NEWLINE = "<br/>";
Maybe drop INTRA_CELL in the defines for better readability.

2020-01-19 07:32 UTC, csholmq commented
@usagi I want to merge this but there are two stoppers.

1. Conflicting file `src/test/excel-markdown-helpers.test.ts`
2. Unable to debug this. Seems to have broken since the last time I managed this. I assume #14 fixes this?

2020-01-19 07:57 UTC, usagi commented
`rebase` is completed. 🚀

2020-01-19 08:40 UTC, csholmq commented
@usagi Doesn't appear to work for me on Win10.

https://docs.google.com/spreadsheets/d/1RHlfdDmaGdCHUuT7rYlAWnuo8zoiP8EHYcAH4zRM4bg/edit?usp=sharing

produces

```
| aaa  | bbb  |
|------|------|
| ccc  | "ddd |
| eee" |
```

2020-01-19 09:06 UTC, csholmq commented
Oh, ok. Found the issue. First execution works fine, but the second is bad. Reason seems to be some kind of escaping when replacing the copy buffer with the original raw data. Something is changed.

2020-01-19 09:07 UTC, usagi commented
Hmm, I only tested from Microsoft Excel, not from Google Spreadsheet. And It's work fine from Microsoft Excel.

![image](https://user-images.githubusercontent.com/115972/72678056-bbbf0000-3ae5-11ea-8f14-df26d2c3df2e.png)

2020-01-19 09:09 UTC, csholmq commented
First execution

`"aaa\tbbb\r\nccc\t"ddd\neee""`

Second execution

`"aaa\tbbb\r\nccc\t"ddd\r\neee""`

2020-01-19 09:09 UTC, usagi commented
> Oh, ok. Found the issue. First execution works fine, but the second is bad. Reason seems to be some kind of escaping when replacing the copy buffer with the original raw data. Something is changed.

Good finding, I could repro too.

2020-01-19 09:11 UTC, usagi commented
Ok, I'll fix.

2020-01-19 09:21 UTC, csholmq commented
Might be an issue with https://github.com/xavi-/node-copy-paste so perhaps difficult to workaround.

If you could also drop the `INTRA_CELL` in the other defines as well and then squash your commits.

2020-01-19 10:03 UTC, usagi commented
> Might be an issue with https://github.com/xavi-/node-copy-paste so perhaps difficult to workaround.

No problems maybe. I have an idea. Plz wait the next fixing.

2020-01-19 10:37 UTC, usagi commented
rebased with:
1. `INTRA_CELL` dropping
2. fixup the pasting issue. -> see src/extension.ts https://github.com/csholmq/vscode-excel-to-markdown-table/pull/15/files#diff-45327f86d4438556066de133327f4ca2R44

2020-01-19 13:52 UTC, merged

2020-01-19 13:53 UTC, csholmq commented
Nice work! Thanks!

I'll add you to the credits and release a new version tonight. Many thanks! 🎉💯