Added ":" as prefix for left aligned headers
csholmq/vscode-excel-to-markdown-table pull request #16
Opened 2020-02-13 22:25 UTC by Markus-Hanisch

fixes issue #12

2020-02-13 22:40 UTC, csholmq commented
Nice!

2020-02-13 22:48 UTC, csholmq commented
@Markus-Hanisch Normally default alignment (`---`) is identical to left alignment (`:---`). This fix clarifies that by making `^l` explicit. That's good.

Problem is that it also removes the default alignment option where no `^[lcr]` prefix defaults to explicit left alignment. I suggest you add a new _default_ alignment and the corresponding logic to it before I merge it.

2020-02-14 17:59 UTC, Markus-Hanisch commented
Hello @csholmq 
Unfortunately, I am not such a good developer as you obviously are. Long story short: I might revert my pull request because I don't know exactly how to adjust your code appropriately.
I assume that it will require 
- an additional option "ALIGNED_DEFAULT_SYNTAX" in [table-alignment-syntax.ts](https://github.com/csholmq/vscode-excel-to-markdown-table/blob/master/src/table-alignment-syntax.ts)
-  modifications in [excel-markdown-helpers.ts](https://github.com/csholmq/vscode-excel-to-markdown-table/blob/master/src/excel-markdown-helpers.ts)" on lines 68 and 111?

Should I make a suggestion / pull request? Would you mind to review, test and adjust or refuse if prefered?

I think what confused me is the fact that in Markdown the header alignment seems to default to centered alignment whereas the alignment of data rows defaults to left alignment.
However, using the colons ":" will adjust header and rows at the same time and there seems no way to align rows and headers separately (references: [1](https://help.github.com/en/github/writing-on-github/organizing-information-with-tables#formatting-content-within-your-table), [2](https://vuepressbook.com/tutorial/tutorial5.html#aligning-text-within-columns)). I try to illustrate with the following example:

*explicit left / center / right data row alignment (both the same)*:
| Heeeeading1 | Heeeeading2 | Heeeeading3 |
|:----------|:---------:|----------:|
| row 1     | row 2     | row 3      |

*explicit left / center / right header alignment (both the same)*:
| Heading1 | Heading2 | Heading3 |
|:----------|:---------:|----------:|
| rooooooooooooooow 1     | rooooooooooooooow 2     | rooooooooooooooow 3      |

*implicit default datarow alignment (left)*:
| Heeeeading1 | Heeeeading2 | Heeeeading3 |
|----------------|----------------|----------------|
| row 1     | row 2     | row 3      |

*implicit default header alignment (centered)*:
| Heading1 | Heading2 | Heading3 |
|----------|---------|----------|
| rooooooooooooooow 1     | rooooooooooooooow 2     | rooooooooooooooow 3      |

Markdown:
```markdown
*explicit left / center / right data row alignment (both the same)*:
| Heeeeading1 | Heeeeading2 | Heeeeading3 |
|:----------|:---------:|----------:|
| row 1     | row 2     | row 3      |

*explicit left / center / right header alignment (both the same)*:
| Heading1 | Heading2 | Heading3 |
|:----------|:---------:|----------:|
| rooooooooooooooow 1     | rooooooooooooooow 2     | rooooooooooooooow 3      |

*implicit default datarow alignment (left)*:
| Heeeeading1 | Heeeeading2 | Heeeeading3 |
|----------------|----------------|----------------|
| row 1     | row 2     | row 3      |

*implicit default header alignment (centered)*:
| Heading1 | Heading2 | Heading3 |
|----------|---------|----------|
| rooooooooooooooow 1     | rooooooooooooooow 2     | rooooooooooooooow 3      |

```

2020-02-14 18:16 UTC, Markus-Hanisch commented
@csholmq I made two additional commit with regard to my suggested modifications. Please review accordingly. Thanks.

2020-02-21 12:02 UTC, csholmq requested changes
I just tested this and it doesn't compile. I don't have time atm to debug it but you should be able to if you open up the project, press F5 och sort out the issues.

When building successfully it will fire up a second instance of VSCode where your version of the extension is loaded so that you can test it out.

2020-02-21 12:02 UTC, csholmq commented on src/excel-markdown-helpers.ts
> +        case ALIGNED_DEFAULT: return ALIGNED_DEFAULT_SYNTAX
This case is covered by the default below. So it can be removed.

2020-02-21 12:02 UTC, csholmq commented on src/excel-markdown-helpers.ts
> +    return ALIGNED_DEFAULT;
Comment needs updating

2020-02-21 12:02 UTC, csholmq commented on src/excel-markdown-helpers.ts
> +        case ALIGNED_DEFAULT: return ALIGNED_DEFAULT;
This case is covered by the default below. So it can be removed.

2021-03-20 14:57 UTC, closed without merging